# data
data_base_path: "../data"
train_csv: "train.csv"
train_images: "train_images"

test_csv: "sample_submission.csv"
test_images: "test_images"

target_col: "label"

# save models
# save to ../models/$backbone/xxxx.pth
model_base_path: '../models/'

# hyperparameters
target_size: 5 # network output size
image_size: 512
seed: 2020
num_workers: 8

# k_folds
k_folds: 5
k_folds_csv: "5folds.csv"

# set distri data parallel
DDP: False
amp: False
apex: False