# data
data_base_path: "../data"
train_csv: "train.csv"
train_images: "train_images"

test_csv: "sample_submission.csv"
test_images: "test_images"

target_col: "label"

# save models
# save to ../models/$backbone + $model_suffix/xxxx.pth
model_base_path: '../models/'
model_suffix: ''

# hyperparameters
target_size: 5 # network output size
image_size: 512
seed: 2020
num_workers: 8
accumulated_gradient: 1

# distance_loss
forward_features: False
distance_loss: False

# k_folds
k_folds: 5
k_folds_csv: "5folds.csv"

# set distri data parallel
DDP: False
port: 12345
amp: False
apex: False