# split train.csv
k_folds: 5

backbone: tf_efficientnet_b4
optimizer: AdamW
batch_size: 16
epochs: 40
min_lr: 1e-6
lr: 1e-3
weight_decay: 2e-4
max_grad_norm: 10
print_freq: 50

transform: "strong_fix"
p: 0.9 # for transform
criterion: LabelSmoothing
smoothing: 0.1
scheduler: CosineAnnealingLR

amp: False
apex: False
DDP: True
norm_confusion_matrix: True
num_workers: 4