# split train.csv
k_folds: 5
data_base_path: "../data2"
k_folds_csv: "5folds2.csv"
seed: 2021

backbone: resnext50_32x4d
optimizer: AdamW
momentum: 0.9
batch_size: 32
accumulated_gradient: 2
epochs: 20
weight_decay: 2e-4
max_grad_norm: 10
print_freq: 100
model_suffix: '_res50d'

transform: "strong_fix2"
p: 0.9 # for transform
criterion: BiTemperedLoss
t1: 0.5
t2: 2.0
# criterion: LabelSmoothing
smoothing: 0.6

# scheduler: GradualWarmupScheduler
# total_epoch: 5
# after_scheduler: CosineAnnealingLR
scheduler: CosineAnnealingLR
lr: 1e-3
min_lr: 1e-5

amp: False
apex: False
DDP: True
norm_confusion_matrix: True
num_workers: 16

cutmix: True
cutmix_prob: 0.2
port: 15555