# split train.csv
k_folds: 5

backbone: tf_efficientnet_b4
optimizer: AdamW
batch_size: 32
image_size: 512
epochs: 20
min_lr: 1e-6
lr: 1e-3
weight_decay: 2e-4
max_grad_norm: 10
print_freq: 100

transform: "strong_fix"
p: 0.9 # for transform
criterion: LabelSmoothing
smoothing: 0.01
scheduler: CosineAnnealingLR
amp: False
apex: False
data_parallel: False
data_parallel_gpus: 4,5,6,7
