# split train.csv
k_folds: 5

backbone: tf_efficientnet_b3
optimizer: AdamP
batch_size: 56
epochs: 30
min_lr: 1e-5
lr: 1e-3
weight_decay: 1e-4
max_grad_norm: 10
print_freq: 100

transform: "strong"
p: 0.9 # for transform
criterion: CrossEntropyLoss
scheduler: CosineAnnealingLR
amp: True