# split train.csv
k_folds: 5

backbone: tf_efficientnet_b4
optimizer: AdamW
batch_size: 28
image_size: 492
epochs: 20
min_lr: 1e-5
lr: 1e-3
weight_decay: 2e-4
max_grad_norm: 10
print_freq: 100

transform: "strong_fix"
p: 0.95 # for transform
criterion: CrossEntropyLoss
scheduler: CosineAnnealingLR
amp: False
apex: False
data_parallel: False
