# split train.csv
k_folds: 5

backbone: tf_efficientnet_b6
optimizer: AdamP
batch_size: 20
epochs: 20
min_lr: 1e-5
lr: 1e-3
weight_decay: 3e-4
max_grad_norm: 10
print_freq: 100

transform: "strong_fix"
p: 0.9 # for transform
criterion: FocalCosineLoss
scheduler: CosineAnnealingLR
amp: True