# split train.csv
k_folds: 5

backbone: tf_efficientnet_b3
optimizer: AdamW
batch_size: 32
epochs: 20
min_lr: 1e-6
lr: 1e-3
momentum: 0.9
weight_decay: 2e-4
max_grad_norm: 10
print_freq: 100

transform: "strong_fix"
p: 0.9 # for transform
criterion: LabelSmoothing
smoothing: 0.05
scheduler: CosineAnnealingLR

amp: False
apex: False
DDP: False
TTA: False

