# split train.csv
k_folds: 5

backbone: tf_efficientnet_b3
optimizer: AdamP
batch_size: 32
epochs: 20
min_lr: 1e-5
lr: 1e-3
weight_decay: 2e-4
max_grad_norm: 10
print_freq: 100

transform: "strong_fix"
p: 0.9 # for transform
criterion: LabelSmoothingLoss
smoothing: 0.1
scheduler: CosineAnnealingLR

amp: False
apex: False
data_parallel_gpus: 4,5,6,7