# predict csv path
output_dir: "../result"
ensemble_method: 'mean'

# models list
model_list: 
  - backbone: 'mobilenetv3_large_100'
    filename:
      - 'fold0_best.pth'
      - 'fold1_best.pth'
      - 'fold2_best.pth'
      - 'fold3_best.pth'
      - 'fold4_best.pth'

# for train ensemble weights
k_folds: 5
batch_size: 64
print_freq: 100

transform: "strong"
p: 0.9 # for transform
criterion: CrossEntropyLoss
scheduler: CosineAnnealingLR
optimizer: AdamW
epochs: 10
min_lr: 1e-5
lr: 1e-3
weight_decay: 1e-4
max_grad_norm: 10