# split train.csv
k_folds: 5

backbone: 'resnext50_32x4d'
lr: 1e-3
weight_decay: 1e-4
batch_size: 32
epochs: 30
max_grad_norm: 50
gradient_accumulation_steps: 1
print_freq: 10

criterion: CrossEntropyLoss
scheduler: ~