k_folds: 5

# models list
model_list: 
  - backbone: 'resnext50_32x4d'
    filename:
      - 'resnext50_32x4d0.pth'
      - 'resnext50_32x4d1.pth'
      - 'resnext50_32x4d2.pth'
      - 'resnext50_32x4d3.pth'
      - 'resnext50_32x4d4.pth'