# predict csv path
output_dir: "../result"

batch_size: 32
ensemble_method: 'mean'

# models list
model_list: 
  - backbone: 'resnext50_32x4d'
    filename:
      - 'fold0_best.pth'
      - 'fold1_best.pth'
      - 'fold2_best.pth'
      - 'fold3_best.pth'
      - 'fold4_best.pth'