# predict csv path
output_dir: "../result"
ensemble_method: 'mean'

# models list
model_list: 
  - backbone: 'mobilenetv3_large_100'
    filename:
      - 'fold0_best.pth'
      - 'fold1_best.pth'
      - 'fold2_best.pth'
      - 'fold3_best.pth'
      - 'fold4_best.pth'

# for train ensemble weights
print_freq: 40
batch_size: 128
transform: "strong"
p: 0.5 # for transform
criterion: CrossEntropyLoss
scheduler: CosineAnnealingLR
optimizer: AdamW
epochs: 20
min_lr: 1e-4
lr: 1e-2
weight_decay: 1e-4
max_grad_norm: 10