k_folds: 5

# models list
model_base_path: '../models/'
model_list: 
  - {backbone: 'resnext50_32x4d', filename: 'resnext50_32x4d0.pth'}
  - {backbone: 'resnext50_32x4d', filename: 'resnext50_32x4d1.pth'}
  - {backbone: 'resnext50_32x4d', filename: 'resnext50_32x4d2.pth'}
  - {backbone: 'resnext50_32x4d', filename: 'resnext50_32x4d3.pth'}
  - {backbone: 'resnext50_32x4d', filename: 'resnext50_32x4d4.pth'}