# split train.csv
k_folds: 5

backbone: 'mobilenetv3_large_100'
optimizer: AdamW
lr: 1e-3
min_lr: 1e-5
weight_decay: 1e-4
batch_size: 32
epochs: 20
max_grad_norm: 10
print_freq: 100

transform: "strong_fix"
p: 0.9 # for transform
criterion: CrossEntropyLoss
scheduler: CosineAnnealingLR

amp: False
apex: False
DDP: False