# split train.csv
k_folds: 5
data_base_path: "../data2"
seed: 42
k_folds_csv: "5folds2.csv"

backbone: tf_mobilenetv3_large_100
optimizer: AdamW
batch_size: 32
accumulated_gradient: 1
epochs: 20
weight_decay: 1e-4
max_grad_norm: 10
print_freq: 100
model_suffix: '_cutmix'

transform: "strong_fix3"
p: 0.9
criterion: TaylorCrossEntropyLoss
# t1: 0.6
# t2: 1.8
# criterion: LabelSmoothing
smoothing: 0.2

# scheduler: GradualWarmupScheduler
# total_epoch: 5
# after_scheduler: CosineAnnealingLR
scheduler: CosineAnnealingLR
lr: 2e-4
min_lr: 1e-5

amp: False
apex: False
DDP: False
norm_confusion_matrix: True
num_workers: 6

cutmix: True
cutmix_prob: 0.5

always_save: False
