# split train.csv
k_folds: 5

backbone: 'resnet50'
lr: 2e-3
min_lr: 1e-4
weight_decay: 1e-4
batch_size: 32
epochs: 10
max_grad_norm: 10
print_freq: 100

criterion: CrossEntropyLoss
scheduler: CosineAnnealingLR
amp: False